apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw
spec:
  selector:
    matchLabels:
      app: apigw
  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
      - name: apigw
        image: priajiabror/apigw:latest
        ports:
        - containerPort: 18083